/**
 * GLOBAL CONFIGURATION FOR HOCHZEITSTAG APP
 */
const HOCHZEITSTAG_CONFIG = {
    // Dates (ISO Format: YYYY-MM-DDTHH:mm:ss)
    weddingDate: "2025-09-06T11:02:00",
    firstContactDate: "2014-01-11T19:02:00",
    firstMeetDate: "2014-04-01T21:02:00", // "Zusammen" / Together

    // Visuals
    backgroundImage: "kiss.jpeg", // Filename in the same directory (or URL)

    // Notification Settings (Placeholder for future functionality)
    emailReminderDaysFirst: 7, // Days before event to send email (First reminder)
    emailReminderDaysSecond: 1, // Days before event to send email (Second reminder)
    emailAddresses: {
        wife: { email: "tanja-risse@gmx.de", name: "Tanja" },
        husband: { email: "klaus@wolfsoft.de", name: "Klaus" }
    },

    // List of humorous and affectionate German quotes/poems (total 120, shorter version)
    quotes: [
        "Liebe ist: zu zweit albern sein.",
        "Wir passen, wie Topf und Deckel.",
        "Ehe: Streit um Fernbedienung, endet mit Lachen.",
        "Zusammen sind wir besser, wie Kaffee & Kuchen.",
        "Mein Lieblingsmensch, trotz letztem Keks.",
        "Liebe: Das Einzige, was mehr wird, wenn man es verschwendet.",
        "Mit dir wird jeder Einkauf zum Abenteuer.",
        "Echte Liebe erträgt auch Schnarchen.",
        "Mein Anker im Sturm, mein Konfetti im Alltag.",
        "Zuhause ist, wo du bist (und WLAN).",
        "Wir: Ein Team für Chaos und Ordnung.",
        "Liebe heißt: immer wieder vertragen.",
        "Mit dir: Jeder Tag ein Feiertag.",
        "Du bist der Grund für mein Handy-Lächeln.",
        "Unsere Liebe: guter Wein, wird besser mit Jahren.",
        "Danke, dass du meine Macken magst.",
        "Wir zwei gegen den Rest der Welt (und Abwasch).",
        "Du bringst mich zum Lachen, auch mürrisch.",
        "Glück ist: herrlich albern sein.",
        "Du bist der Zucker in meinem Kaffee.",
        "Egal wohin, Hauptsache zusammen.",
        "Mit dir macht sogar Nichtstun Spaß.",
        "Du bist mein Happy Place.",
        "Liebe ist: blind verstehen.",
        "Ich mag dich mehr als Pizza.",
        "Du und ich – das passt.",
        "Mein Herz schlägt im Takt von deinem.",
        "Deine Umarmung: mein Lieblingsort.",
        "Zusammen ist man weniger allein.",
        "Du bist mein Lieblings-Nervzwerg.",
        "Ich liebe dich mehr als Kaffee (sag's nicht).",
        "Wir sind wie Pech und Schwefel, nur hübscher.",
        "Du hast den Schlüssel zum Herzen (und Kühlschrank).",
        "Liebe: Du lässt mir die letzte Schokolade.",
        "Du bist der Grund, warum ich aufstehe (meistens).",
        "Mit dir ist sogar der Abwasch erträglich.",
        "Wir sind das perfekte Chaos.",
        "Du bist mein liebster Zeitvertreib.",
        "Ich liebe dich, auch wenn du hungrig bist.",
        "Du bist mein persönlicher Superheld (ohne Umhang).",
        "Zusammen sind wir unschlagbar (im Faulenzen).",
        "Du bist mein Lieblingsmensch, Punkt.",
        "Liebe ist: schweigend anschreien können.",
        "Du bist süßer als Zuckerwatte.",
        "Ich würde mein Handy für dich weglegen.",
        "Du bist der Käse auf meiner Pizza.",
        "Wir passen zusammen wie Pommes und Ketchup.",
        "Du bist mein Einhorn in Pferdeherde.",
        "Liebe ist: gemeinsam dick werden.",
        "Du bist der Grund für mein Dauergrinsen.",
        "Ich liebe dich mehr als gestern (weniger als morgen).",
        "Du bist meine bessere, vernünftigere Hälfte.",
        "Mit dir kann man Pferde stehlen (und Ponys).",
        "Du bist mein Lieblings-Kuscheltier.",
        "Liebe: Decke teilen (widerwillig).",
        "Du bist der Hit in meinen Charts.",
        "Ich folge dir (außer aufs Klo).",
        "Du bist mein Highlight des Tages.",
        "Wir sind Bonnie & Clyde, ohne Banküberfall.",
        "Du bist mein 6er im Lotto.",
        "Ich liebe dich bis zur Unendlichkeit.",
        "Du bist mein Fels und mein Kissen.",
        "Mit dir wird's nie langweilig.",
        "Du bist mein Lieblings-Abenteuer.",
        "Liebe ist: blind vertrauen (trotzdem Google Maps checken).",
        "Du bist mein Sternenhimmel.",
        "Ich hab dich zum Fressen gern.",
        "Du bist mein Lieblings-Gedanke vor dem Einschlafen.",
        "Wir sind ein Dream-Team.",
        "Du bist mein Sonnenschein, auch nachts.",
        "Ich liebe dich mehr als Schokolade.",
        "Du bist mein Herzblatt.",
        "Mit dir ist das Leben ein Ponyhof.",
        "Du bist mein allerliebster Lieblingsmensch.",
        "Liebe ist: gegenseitig Sätze beenden.",
        "Du bist der Grund, warum ich glücklich bin.",
        "Ich bin süchtig nach dir.",
        "Du bist mein Zuhause.",
        "Wir sind einfach füreinander gemacht.",
        "Zwei Herzen, ein Beat, unser Rhythmus.",
        "Liebe ist: den anderen in Jogginghose lieben.",
        "Du bist mein Happy End, jeden Tag.",
        "Unsere Liebe: mehr als tausend Worte.",
        "Ein Blick sagt mehr als jede Rede.",
        "Mit dir ist jeder Moment Gold wert.",
        "Du machst mein Leben heller.",
        "Unsere Herzen tanzen im Gleichklang.",
        "Du bist mein Traum, der wahr wurde.",
        "Ein Leben ohne dich? Undenkbar!",
        "Liebe ist die schönste Reise.",
        "Du bist das Puzzleteil, das fehlte.",
        "Jeder Tag mit dir ist ein Geschenk.",
        "Du gibst meinem Leben Sinn.",
        "Du bist mein Anker, mein Halt.",
        "Unsere Liebe: ein unendliches Band.",
        "Du bist mein größtes Abenteuer.",
        "Mit dir ist alles leichter.",
        "Du bist mein Lächeln, meine Freude.",
        "Unsere Liebe wächst jeden Tag.",
        "Du bist mein Herz, meine Seele.",
        "Du bist der Grund für mein Glück.",
        "Ein Kuss von dir: mein Lieblingsgefühl.",
        "Du bist mein Zuhause, wo immer wir sind.",
        "Unsere Liebe: stärker als alles.",
        "Du bist mein Wunsch, der in Erfüllung ging.",
        "Mit dir ist jeder Tag ein Gedicht.",
        "Du bist mein Held, mein Retter.",
        "Unsere Liebe: ein ewiges Feuer.",
        "Du bist mein Schatz, mein größter Gewinn.",
        "Du machst mich komplett.",
        "Unsere Herzen sind verbunden.",
        "Du bist mein Glück, mein Schicksal.",
        "Mit dir ist jeder Weg das Ziel.",
        "Du bist mein Stern, der leuchtet.",
        "Unsere Liebe: unendlich und rein.",
        "Du bist mein Leben, mein Atem.",
        "Du bist mein Licht, meine Sonne.",
        "Unsere Liebe: ein Wunder, das bleibt.",
        "Du bist mein Alles, mein Nichts.",
        "Du bist meine Ewigkeit."
    ]
};
